### ISSUE TITLE
Dada mis-behaves when using a Reverse Proxy

### ISSUE THREAD

**Issue by PaulKlumpp** [justingit/dada-mail#691]
Using a reverse proxy that does SSL-termination. So the reverse proxy forwards all requests to:

http://localhost:10083/dada/installer/install.cgi  
Actually, I put Dada into a Docker Container.

The installer outputs html with links that use "http". It assumes the scheme is http, but it is not.
Also it assumes "/dada/" as path. But Path in the reverse proxy is just "/".

So, this comes down to:
- Dada should omit using a scheme (http(s))
- Dada should work with relative paths to its own script files.. also, no scheme needed.

**Comment by justingit** [comment]
Makes sense, I haven't tried putting working with Dada Mail in Docker, so I'm not surprised it is misbehaving. 

What docs are you following to try to make this work?

**Comment by PaulKlumpp** [comment]
Sorry for the late reply. It totally got out of sight.

I am not following any special documentation. I tried dockerizing Dadamail myself. I created the following Dockerfile contents to define the image:
```
FROM uniqrn/perl-fcgi
MAINTAINER Paul Klumpp (paul@klumpp.de)
ENV HTDOCS /usr/local/apache2/htdocs
ENV DATA /opt/dada
ENV WDIR /root/wdir
VOLUME ["$DATA", "$HTDOCS"]

RUN usermod -d $DATA daemon
RUN mkdir -p $DATA && chown -R daemon:daemon $DATA && chmod 2755 $DATA
RUN mkdir -p $WDIR

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y apt-utils
RUN apt-get install -y cron curl build-essential vim

RUN apt-get install -y libxml-perl libsoap-lite-perl libdbd-mysql-perl libnet-dns-perl libhtml-tree-perl libio-socket-ssl-perl libcrypt-ssleay-perl libxmlrpc-lite-perl libgravatar-url-perl
#ENV PERL_MM_USE_DEFAULT=1
#ENV PERL_EXTUTILS_AUTOINSTALL="--defaultdeps"
RUN curl -L https://cpanmin.us | perl - --force App::cpanminus
RUN apt-get install -y pkg-config libgd-dev libcurl4-openssl-dev libxml2-dev
RUN cpanm -i Image::Resize WWW::StopForumSpam CSS::Inliner Bundle::DadaMail # this failed so hard before.

COPY httpd.conf /usr/local/apache2/conf/

WORKDIR $WDIR
#COPY ./dada-10_7_0.tar.gz ./
RUN pwd && curl -L -O https://netcologne.dl.sourceforge.net/project/dadamail/dada-10_7_0.tar.gz
RUN curl -L -O https://raw.github.com/justingit/dada-mail/v10_7_0-stable_2017_07_05/uncompress_dada.cgi
RUN ls -l
RUN cd $WDIR && /usr/bin/perl -T $WDIR/uncompress_dada.cgi

RUN echo '*/5 * * * * /usr/bin/curl --user-agent "Mozilla/5.0 (compatible;)" --silent --get --url http://localhost/dada/mail.cgi/_schedules/_all/_all/_silent/' > /var/spool/cron/crontabs/root
RUN mkdir -p $HTDOCS/dada_mail_support_files && chown -R daemon:daemon $HTDOCS && chmod 2755 $HTDOCS


USER root
CMD if [ ! -d '/usr/local/apache2/htdocs/dada' ]; then cp -vr $WDIR/* $HTDOCS ; fi ; \
    if [ ! -d '/usr/local/apache2/htdocs/dada/dada_mail_support_files' ]; then  \
      mkdir -p $HTDOCS/dada_mail_support_files ; fi ; \
    chown -R daemon:daemon $HTDOCS $DATA && chmod 2755 $HTDOCS && \
    service cron start && httpd-foreground

# http://localhost:8080/dada/installer/install.cgi
```
Building it with: docker build --pull . -t dadamail

The compose file I did, looks like this:
```
version: "3"
services:
  dada:
    image: dadamail
    container_name: dada_dada
    restart: always
    ports:
      - "10083:80"
    volumes:
      - dada-home:/opt/dada
      - dada-htdocs:/usr/local/apache2/htdocs

  mysql:
    image: mariadb
    container_name: dada_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s3crets4uc3
      MYSQL_DATABASE: dada
      MYSQL_USER: dada
      MYSQL_PASSWORD: s4uc3s3cret
    volumes:
      - dada-mysql:/var/lib/mysql

volumes:
  dada-home:
  dada-htdocs:
  dada-mysql:
```

All in all, it kinda gets weird because of the moving parts.
